apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-sql-test-{{ randAlphaNum 5 | lower }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-sql-test
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: {{ .Release.Name }}-sql-test
      image: {{ .Values.Master.Image }}:{{ .Values.Master.ImageTag }}
      command: ["{{ .Values.Spark.Path }}/bin/spark-sql", "--master",
                "spark://{{ .Release.Name }}-master:{{ .Values.Master.ServicePort }}", "-e",
                "show databases;"]
  restartPolicy: Never
