kind: Service
apiVersion: v1
metadata:
  name: {{ template "workerlb-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
spec:
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
  ports:
  - name: driverport
    port: 8085
    targetPort: 8085
  - name: webui
    port: 8081
    targetPort: 8081
  - name: monitor
    port: 4040
    targetPort: 4040
  - name: server
    port: 8888
    targetPort: 8888
  - name: misc
    port: 8889
    targetPort: 8889
  - name: webui2
    port: 8080
    targetPort: 8080
  type: LoadBalancer
